name: 'Text on github contribution graph'
inputs:
  github_user_name:
    description: 'GitHub user name'
    default: 'jasineri'
    required: true
  text:
    description: 'Text on contributions graph'
    default: 'JASINERI'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
