# GitHub Action generates SVG from a contribution graph with custom text.

name: Generate SVG

# Controls when the action will run. This action runs every 6 hours.

on:
  schedule:
      # every 24 hours
    - cron: "* */24 * * *"

# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Generates the snake  
      - uses: partinis/gitpaint@v1
        with:
          github_user_name: jasineri
          text: JASINERI
          svg_file_name: graph.svg
          
      - uses: jasineri/simple-push-action@v1
        with:
          # Files pattern to add, wildcards supported
          # Optional, default: ./*.*
          file_pattern: ./*.svg
